name: Build, Sitemap and Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  sitemap-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 1. サイトマップの自動生成
      - name: Generate the sitemap
        id: sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://sesso-richu.github.io/bgssearcher/

      # 2. 変更があればリポジトリにコミット
      - name: Commit sitemap
        run: |
          if [[ `git status --porcelain sitemap.xml` ]]; then
            git config --global user.name 'github-actions[bot]'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add sitemap.xml
            git commit -m "Automated sitemap update [skip ci]"
            git push
          fi

      # 3. GitHub Pagesへ公開準備（アーティファクト作成）
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      # 4. GitHub Pagesへデプロイ
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
